# Generated by Django 6.0.1 on 2026-01-16 21:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Libreria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre_libreria",
                    models.CharField(
                        max_length=100,
                        unique=True,
                        verbose_name="Nombre de la libreria",
                    ),
                ),
                (
                    "direccion_fisica",
                    models.CharField(max_length=200, verbose_name="Dirección"),
                ),
                (
                    "numero_estantes",
                    models.IntegerField(verbose_name="numero de estantes"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Empleado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre_completo", models.CharField(max_length=200)),
                (
                    "cargo_empleado",
                    models.CharField(
                        help_text="Ejemp: Vendedor, Cajero", max_length=100
                    ),
                ),
                (
                    "salario_mensual",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "libreria",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="empleados",
                        to="gestionLib.libreria",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Libro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo_libro", models.CharField(max_length=200)),
                ("autor_principal", models.CharField(max_length=200)),
                ("genero_literario", models.CharField(max_length=200)),
                ("precio_venta", models.DecimalField(decimal_places=2, max_digits=10)),
                ("numero_paginas", models.IntegerField()),
                (
                    "empleado",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gestionLib.empleado",
                        verbose_name="registrado por",
                    ),
                ),
            ],
        ),
    ]
