# Generated by Django 6.0.1 on 2026-01-18 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("gestionLib", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="libreria",
            old_name="direccion_fisica",
            new_name="direccion_lib",
        ),
        migrations.RenameField(
            model_name="libro",
            old_name="genero_literario",
            new_name="genero_lit",
        ),
    ]
